# Generated by Django 5.2.11 on 2026-02-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('suffix_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('platoon', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('year_level', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Ongoing', max_length=50)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('language_spoken', models.CharField(blank=True, max_length=255, null=True)),
                ('combat_boots_size', models.CharField(blank=True, max_length=20, null=True)),
                ('uniform_size', models.CharField(blank=True, max_length=20, null=True)),
                ('bullcap_size', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('rotc_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('mobilization_center', models.CharField(blank=True, max_length=255, null=True)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cadets',
                'indexes': [models.Index(fields=['student_id'], name='cadets_student_6c4df6_idx'), models.Index(fields=['company', 'platoon'], name='cadets_company_dddff1_idx'), models.Index(fields=['is_archived'], name='cadets_is_arch_b34ade_idx')],
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_present', models.IntegerField(default=0)),
                ('merit_points', models.IntegerField(default=0)),
                ('demerit_points', models.IntegerField(default=0)),
                ('prelim_score', models.FloatField(blank=True, null=True)),
                ('midterm_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('cadet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cadets.cadet')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
    ]
