# Generated by Django 5.2.11 on 2026-02-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('suffix_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('afpsn', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('language_spoken', models.CharField(blank=True, max_length=255, null=True)),
                ('combat_boots_size', models.CharField(blank=True, max_length=20, null=True)),
                ('uniform_size', models.CharField(blank=True, max_length=20, null=True)),
                ('bullcap_size', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('rotc_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('mobilization_center', models.CharField(blank=True, max_length=255, null=True)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('has_seen_guide', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_staff',
                'indexes': [models.Index(fields=['email'], name='training_st_email_49a773_idx'), models.Index(fields=['is_archived'], name='training_st_is_arch_7996a6_idx')],
            },
        ),
    ]
