# Generated by Django 5.2.11 on 2026-02-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritDemeritLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('merit', 'Merit'), ('demerit', 'Demerit')], max_length=10)),
                ('points', models.IntegerField()),
                ('reason', models.TextField()),
                ('issued_by_user_id', models.IntegerField()),
                ('issued_by_name', models.CharField(max_length=255)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_demerit_logs', to='cadets.cadet')),
            ],
            options={
                'db_table': 'merit_demerit_logs',
                'indexes': [models.Index(fields=['cadet', 'date_recorded'], name='merit_demer_cadet_i_c4993f_idx')],
            },
        ),
    ]
