# Generated by Django 6.0.2 on 2026-02-23 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('suffix_name', models.CharField(blank=True, default='', max_length=20)),
                ('rank', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('religion', models.CharField(blank=True, default='', max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('course', models.CharField(blank=True, default='', max_length=100)),
                ('year_level', models.CharField(blank=True, default='', max_length=20)),
                ('school_year', models.CharField(blank=True, default='', max_length=20)),
                ('battalion', models.CharField(blank=True, default='', max_length=50)),
                ('company', models.CharField(blank=True, default='', max_length=50)),
                ('platoon', models.CharField(blank=True, default='', max_length=50)),
                ('cadet_course', models.CharField(blank=True, default='', max_length=100)),
                ('semester', models.CharField(blank=True, default='', max_length=20)),
                ('corp_position', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='Ongoing', max_length=20)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('profile_pic', models.CharField(blank=True, default='', max_length=255)),
                ('attendance_present', models.IntegerField(default=0)),
                ('attendance_total', models.IntegerField(default=15)),
                ('merit_points', models.IntegerField(default=0)),
                ('demerit_points', models.IntegerField(default=0)),
                ('prelim_score', models.FloatField(default=0)),
                ('midterm_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('subject_score', models.FloatField(default=0)),
                ('attendance_score', models.FloatField(default=0)),
                ('aptitude_score', models.FloatField(default=0)),
                ('final_grade', models.FloatField(default=0)),
                ('transmuted_grade', models.CharField(default='5.00', max_length=4)),
                ('grade_remarks', models.CharField(blank=True, default='', max_length=32)),
                ('grade_status', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeritDemeritLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('merit', 'Merit'), ('demerit', 'Demerit')], max_length=10)),
                ('points', models.IntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('issued_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_logs', to='rgms.cadet')),
            ],
        ),
    ]
