# Generated by Django 6.0.2 on 2026-02-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, default='', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix_name', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('role', models.CharField(blank=True, default='Instructor', max_length=100)),
                ('profile_pic', models.CharField(blank=True, default='', max_length=255)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
