# Generated by Django 6.0.2 on 2026-02-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgms', '0002_trainingstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=150, unique=True)),
                ('first_name', models.CharField(default='System', max_length=100)),
                ('last_name', models.CharField(default='Administrator', max_length=100)),
                ('email', models.EmailField(default='msusndrotcunit@gmail.com', max_length=254)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='admin_profiles/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
