# Generated by Django 6.0.2 on 2026-02-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgms', '0003_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadet',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cadet_profiles/'),
        ),
        migrations.AlterField(
            model_name='trainingstaff',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
    ]
