export const addReportHeader = (doc, { title, dateText, leftLogo, rightLogo }) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const headerY = 12;
  try {
    if (leftLogo) {
      doc.addImage(leftLogo, 'PNG', margin, headerY, 18, 18);
    }
  } catch {}
  try {
    if (rightLogo) {
      doc.addImage(rightLogo, 'PNG', pageWidth - margin - 18, headerY, 18, 18);
    }
  } catch {}
  doc.setFontSize(10);
  doc.text('MSU-SND ROTCU', margin + 22, headerY + 6);
  doc.text(dateText || new Date().toLocaleDateString(), pageWidth - margin - 20, headerY + 6);
  doc.setFontSize(16);
  doc.text(title || 'Report', pageWidth / 2, headerY + 18, { align: 'center' });
};

export const addReportFooter = (doc) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  doc.setFontSize(8);
  const text = `Generated by MSU-SND RGMS • Page ${doc.getCurrentPageInfo().pageNumber}`;
  doc.text(text, pageWidth / 2, pageHeight - 8, { align: 'center' });
};

export const addSignatories = (doc, startY, { preparedBy, preparedRole, certifiedBy, certifiedRole }) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  let y = startY + 10;
  const maxY = doc.internal.pageSize.getHeight() - 20;
  if (y > maxY) {
    doc.addPage();
    y = 20;
  }
  doc.setFontSize(10);
  doc.text('Prepared By:', margin, y);
  doc.text('CERTIFIED CORRECT:', pageWidth - margin - 70, y);
  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.text(preparedBy || 'Wilmer B Montejo', margin, y);
  doc.text(certifiedBy || 'INDIHRA D TAWANTAWAN', pageWidth - margin - 70, y);
  doc.setFont('helvetica', 'normal');
  y += 5;
  doc.text(preparedRole || 'SSg (Inf) PA • Admin NCO', margin, y);
  doc.text(certifiedRole || 'LTC (RES) PA • Commandant', pageWidth - margin - 70, y);
};
