# Generated by Django 5.2.11 on 2026-02-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('cadet', 'Cadet'), ('training_staff', 'Training Staff')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('cadet_id', models.IntegerField(blank=True, null=True)),
                ('staff_id', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_location_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['role'], name='users_role_0ace22_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_alerts', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('activity_updates', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('compact_mode', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='blue', max_length=50)),
                ('custom_bg', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='authentication.user')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
