# Generated by Django 5.2.11 on 2026-02-25 17:01

from django.db import migrations


def add_default_settings(apps, schema_editor):
    """Add default system settings."""
    SystemSettings = apps.get_model('system', 'SystemSettings')
    
    default_settings = [
        {'key': 'school_year', 'value': '2024-2025'},
        {'key': 'semester', 'value': '1st'},
        {'key': 'current_battalion', 'value': 'MSU-SND ROTC'},
        {'key': 'maintenance_mode', 'value': 'false'},
    ]
    
    for setting in default_settings:
        SystemSettings.objects.get_or_create(
            key=setting['key'],
            defaults={'value': setting['value']}
        )


def remove_default_settings(apps, schema_editor):
    """Remove default system settings (reverse migration)."""
    SystemSettings = apps.get_model('system', 'SystemSettings')
    
    default_keys = ['school_year', 'semester', 'current_battalion', 'maintenance_mode']
    SystemSettings.objects.filter(key__in=default_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_settings, remove_default_settings),
    ]
