# Generated by Django 5.2.11 on 2026-02-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadets', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_days',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendanceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.trainingstaff')),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='attendance.trainingday')),
            ],
            options={
                'db_table': 'staff_attendance_records',
                'unique_together': {('training_day', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='ExcuseLetter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_absent', models.DateField()),
                ('reason', models.TextField()),
                ('file_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuse_letters', to='cadets.cadet')),
                ('training_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.trainingday')),
            ],
            options={
                'db_table': 'excuse_letters',
                'indexes': [models.Index(fields=['cadet', 'status'], name='excuse_lett_cadet_i_8d939f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='cadets.cadet')),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.trainingday')),
            ],
            options={
                'db_table': 'attendance_records',
                'indexes': [models.Index(fields=['training_day', 'status'], name='attendance__trainin_c209f1_idx')],
                'unique_together': {('training_day', 'cadet')},
            },
        ),
    ]
