# Generated by Django 5.2.11 on 2026-02-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
    ]
